name: mobileplatform10
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.7.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.0.3
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.8.1
  shared_preferences: ^2.0.13
  http: ^0.13.4
  shelf: ^1.3.0
  shelf_router: ^1.1.0
  shelf_static: ^1.0.0
  intl: ^0.17.0
  image_picker: any
  firebase_storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/야구공.png
    - assets/images/컴프야2.jpg
    - assets/images/기사.png
    - assets/images/자유게시판.jpg
    - assets/images/댓글단글.jpg
    - assets/images/불꽃.png
    - assets/images/트로피.png
    - assets/images/손흔들기.png
    - assets/images/프로필누끼.png
    - assets/images/홈 화면.png
    - assets/images/로그인화면.JPG

